"""empty message

Revision ID: 6ccab5454862
Revises: 
Create Date: 2021-06-03 17:39:33.996678

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from entities.ideas_entity import IdeaEntity

# revision identifiers, used by Alembic.
revision = '6ccab5454862'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_idea',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False),
                    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='修改时间'),
                    sa.Column('last_update_time', sa.DATETIME(), nullable=True, comment='最近修改时间'),
                    sa.Column('title', sa.VARCHAR(length=255), server_default='', nullable=True, comment='备忘录标题'),
                    sa.Column('level', sa.SMALLINT(), server_default=sa.text('0'), nullable=True, comment='状态'),
                    sa.Column('text', sa.Text(), nullable=True, comment='备忘录内容'),
                    sa.Column('is_done', sa.BOOLEAN(), server_default=sa.text('false'), nullable=True, comment='是否完成'),
                    sa.Column('done_at', sa.DATETIME(), nullable=True, comment='完成时间'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='备忘录表')
    op.create_index(op.f('ix_t_idea_last_update_time'), 't_idea', ['last_update_time'], unique=False)
    op.create_index(op.f('ix_t_idea_title'), 't_idea', ['title'], unique=False)
    # ### end Alembic commands ###

    # init data
    bind = op.get_bind()
    session = Session(bind=bind)
    instance = IdeaEntity(title="初始化文档！")
    session.add(instance)
    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_idea_title'), table_name='t_idea')
    op.drop_index(op.f('ix_t_idea_last_update_time'), table_name='t_idea')
    op.drop_table('t_idea')
    # ### end Alembic commands ###
